### ISSUE TITLE
OWL-ViTv2:  No matching distribution found for jax>=0.4.3

### ISSUE THREAD

**Issue by Eureka2001** [google-research/scenic#1012]
**Issue Description:**

I encountered an error while trying to install the OWL-ViTv2 package following the installation instructions provided [here](https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit#installation). My system specifications are as follows:

- Python version: 3.7.12
- OS version: Linux ubuntu 4.15.0-213-generic x86_64
- CUDA Version: 11.4

According to the OWL-ViTv2 installation documentation provided [here](https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit#installation), Python 3.7 is acceptable. However, when attempting to install the required dependencies, I encountered an error related to the JAX package.

I followed the JAX installation instructions provided [here](https://jax.readthedocs.io/en/latest/installation.html#nvidia-gpu) and installed JAX version 0.3.25 using CUDA 11 installation. Here are the commands I executed:

```bash
pip install --upgrade pip

# CUDA 11 installation
# Note: wheels only available on Linux.
pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

However, when I attempted to install the Scenic package using the provided instructions:

```bash
git clone https://github.com/google-research/scenic.git
cd ~/scenic
python -m pip install -vq .
```

I encountered the following error:

```
ERROR: Could not find a version that satisfies the requirement jax>=0.4.3 (from scenic) (from versions: 0.0, 0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.18, 0.1.19, 0.1.20, 0.1.21, 0.1.22, 0.1.23, 0.1.24, 0.1.25, 0.1.26, 0.1.27, 0.1.28, 0.1.29, 0.1.30, 0.1.31, 0.1.32, 0.1.33, 0.1.34, 0.1.35, 0.1.36, 0.1.37, 0.1.38, 0.1.39, 0.1.40, 0.1.41, 0.1.42, 0.1.43, 0.1.44, 0.1.45, 0.1.46, 0.1.47, 0.1.48, 0.1.49, 0.1.50, 0.1.51, 0.1.52, 0.1.53, 0.1.54, 0.1.55, 0.1.56, 0.1.57, 0.1.58, 0.1.59, 0.1.60, 0.1.61, 0.1.62, 0.1.63, 0.1.64, 0.1.65, 0.1.66, 0.1.67, 0.1.68, 0.1.69, 0.1.70, 0.1.71, 0.1.72, 0.1.73, 0.1.74, 0.1.75, 0.1.76, 0.1.77, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.2.15, 0.2.16, 0.2.17, 0.2.18, 0.2.19, 0.2.20, 0.2.21, 0.2.22, 0.2.24, 0.2.25, 0.2.26, 0.2.27, 0.2.28, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13, 0.3.14, 0.3.15, 0.3.16, 0.3.17, 0.3.19, 0.3.20, 0.3.21, 0.3.22, 0.3.23, 0.3.24, 0.3.25)
ERROR: No matching distribution found for jax>=0.4.3
```

Upon further investigation, I found that JAX version 0.4.3 requires at least Python 3.8, as mentioned in the [jax_cuda_releases](https://storage.googleapis.com/jax-releases/jax_cuda_releases.html) page.

**Request:**

Could you please provide guidance on how to resolve this issue? Is there a workaround available for using Scenic with Python 3.7, or should I consider upgrading to Python 3.8?

Thank you for your assistance.

---

**Comment by Curry-Christopher** [comment]
I had the same problem. But when I changed the version of python from 3.7 to 3.10, it seemed to work. The minilab of owl_vit is also using python3.10.

**Comment by Eureka2001** [comment]
@Curry-Christopher Thank you. I attempted the installation on Python 3.8, but encountered numerous errors when installing the `big_vision` package. I'll give it another shot on Python 3.10.
I regret that this model cannot run on Python 3.7. If I upgrade to 3.10, it's likely that my other packages won't work. I hope the repository maintainer will promptly provide updated installation instructions in the official documentation, so that others won't encounter the same issue as I did, starting from Python 3.7.

**Comment by DishantMewada** [comment]
I installed the dependencies on python=3.10 and installed big_vision as well on my local machine. There were no errors during the installation.

But I am getting the error while running any given code. eg.

```
python -m scenic.projects.owl_vit.main \
  --alsologtostderr=true \
  --workdir=/tmp/training \
  --config=scenic/projects/owl_vit/configs/clip_b32.py
```
Error: AttributeError: module 'jax.random' has no attribute 'PRNGKeyArray'

[req.txt](https://github.com/google-research/scenic/files/15110766/req.txt)

I have attached my requirements.txt file.

Please let me know where I am going wrong.

Thank you.

**Comment by DishantMewada** [comment]
I solved it with 
#1043
