### ISSUE TITLE
Useful for Transfer learning?

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [google-research/scenic#112]
Is it possible to use this TokenLearner within pretrained ViT models for transfer learning? If so, have you seen similar performance benefits?

**Comment by MostafaDehghani** [comment]
Thank you @MaxPowerWasTaken for the question. If you mean initializing the normal transformer layers from a pretrained ViT, we have tried this. This, unfortunately, doesn't help when there are TokenLearners in between ViT layers.

**Comment by MostafaDehghani** [comment]
Closing this issue, but feel free to reopen if you have more questions or comments.
