### ISSUE TITLE
Support alternative data_augmentations in imagenet_dataset

### ISSUE THREAD

**Issue by ryanccarelli** [google-research/scenic#143]
We are interested in using scenic's dataset_lib for a self-supervised learning project. The current imagenet_dataset is limited to either "default" augmentation (random crop, reshape, flip) or "None" (center crop, reshape). Some self-supervised learning models rely on alternative augmentations like random_resized_crop.

I could PR, (a) a solution that allows users to pass arbitrary preprocessing functions or (b) add a branch  to the current logic for ssl preprocessing. Is this something that scenic would support? Is there a  preference for one of these solutions?

**Comment by MostafaDehghani** [comment]
Hi @ryanccarelli, 

Thanks for your interest in Scenic and this is exciting that you are considering Scenic for your self-supervised learning project. 
We have a much more flexible and complete input-pipeline internally (that is somehow inline with proposal (a) from you) and we are in the are in the process of open-sourcing it. So hopefully soon, we will have that in Scenic.  I can keep this issue open and comment on it as soon as the complete input pipeline is open-sourced. 

CCing @andsteing.

**Comment by ryanccarelli** [comment]
Thank you for your fast response! It would be great if you could share an approximate timeline (weeks? months?) so we can plan around this

**Comment by MostafaDehghani** [comment]
Sorry for a bit of delay! I was checking with people about the timeline and I think the part that is related to your need can be open-sourced sooner than the rest and I can spend some time to hopefully get it out in a few days.

**Comment by ryanccarelli** [comment]
Thank you again, this project has been very useful for us

**Comment by MostafaDehghani** [comment]
An input pipeline that is much more flexible is now open-sourced. I also released some config files in #148 To show how to use this pipeline. Please let us know if you had any question or any issue.
