### ISSUE TITLE
Working with Imagenet-21K 

### ISSUE THREAD

**Issue by moabarar** [google-research/scenic#162]
Hi, 

Thanks again for this wonderful library!
This is not really an issue - sort of a feature request. 
What would be the best way to work with ImageNet-21K using Scenic?
TFDS support only the ImageNet-1K dataset.

**Comment by MostafaDehghani** [comment]
Hi @moabarar,

We can release the config files for standard hyperparameter for training different models on ImageNet-21k as well as the  preprocessing when it becomes available on TFDS. 

Unfortunately, [it seems](https://github.com/tensorflow/datasets/issues/3414) this is not the case yet.  I'll ask around what is the state of it and will keep you posted on it.

**Comment by moabarar** [comment]
Thanks Mostafa for the reply!

**Comment by MostafaDehghani** [comment]
I checked internally and the TFDS team is super busy with higher priorities than adding new datasets, but they are happy to get PR for adding im21k to TFDS.

**Comment by MostafaDehghani** [comment]
Closing this issue as this is mainly related to TFDS and at this point and we don't have any solution for Scenic users. But I keep following up internally on how we can facilitate this request.
