### ISSUE TITLE
_IMPORT_TABLE entry in datasets.py for the DETR project?

### ISSUE THREAD

**Issue by briancheung** [google-research/scenic#189]
Is there a dataset available for the DETR configuration that can be added to the _IMPORT_TABLE here?
https://github.com/google-research/scenic/blob/ed176cb0bd62345102a560736fc5a4a3b1561161/scenic/dataset_lib/datasets.py#L34

For the DETR project which has this dataset name?

https://github.com/google-research/scenic/blob/ed176cb0bd62345102a560736fc5a4a3b1561161/scenic/projects/baselines/detr/configs/detr_config.py#L19

**Comment by MostafaDehghani** [comment]
Thank you @briancheung for bringing this to our attention. Adding `coco_detr_detection` to the dataset registry got omitted in the export to open-source. 
#190  fixes this issue!
