### ISSUE TITLE
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists

### ISSUE THREAD

**Issue by hillaric** [google-research/scenic#216]
When I try to fix this bug, someone propose to change the version of keras=2.6.0， but it does not work for this project, could anyone give some suggestions?

**Comment by MostafaDehghani** [comment]
#213 could be relevant to your issue. 
This seems like a bug in Keras, but we will look into and see if we can get around it.

**Comment by hillaric** [comment]
I fix this bug by uninstall keras-nightly. However, another appear, "the per-host batch size must be equal to the number of local devices. This ensures that each TPU device is processing different views of the same original video".  I found jax.local_device_count() = 1, it should be 8. The question is that jax can not find 8 GPUs, anyone could give some help?
