### ISSUE TITLE
OWL-ViT checkpoints not found

### ISSUE THREAD

**Issue by itaicaspi-mirrori** [google-research/scenic#309]
Thanks for the great work!

I am getting an error when trying to download any of the checkpoints listed in the main project page:
https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit

This is the error:
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: scenic-bucket/owl_vit/checkpoints/clip_vit_l14_d83d374</Details>
</Error>
```

**Comment by mjlm** [comment]
Hi, thanks for your interest! The checkpoints will be available in a few hours.
