### ISSUE TITLE
Error running OWL-ViT Colab

### ISSUE THREAD

**Issue by drchrisscheier** [google-research/scenic#315]
Hi there,

thank you very much for the extremely impressive work on OWL-ViT and for providing code, checkpoints and even a Colab to try it.

When running the Colab "as is", I am getting this error: 
ScopeParamShapeError: Inconsistent shapes between value and initializer for parameter "positional_embedding" in "/clip/text": (16, 512), (15, 512)

it would be great if you can let us know how to fix this. 
Thank you!
Chris

**Comment by mjlm** [comment]
Hi Chris,
Thanks for your interest! Some bugs always slip through...this should be fixed now. Please don't hesitate to reach out again if you find other issues or have any questions.

**Comment by NielsRogge** [comment]
It's not fixed yet.. running the notebook in Colab, the error now is:

```
AttributeError                            Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/ml_collections/config_dict/config_dict.py](https://localhost:8080/#) in __getattr__(self, attribute)
    827       return self[attribute]
    828     except KeyError as e:
--> 829       raise AttributeError(e)
    830 
    831   def __setitem__(self, key, value):

AttributeError: "'max_query_length'"
```
I fixed it manually by padding the queries myself, as follows:

```
text_queries = ['human face', 'space shuttle']
tokenized_queries = np.array([module.tokenize(q) for q in text_queries])
# pad to max length (16 tokens)
pad = np.array([[0,0]])
tokenized_queries = np.concatenate((tokenized_queries, pad.T), axis=1)
```

**Comment by drchrisscheier** [comment]
Hi there, 
thank you very much for the quick reply and fix!
Best
Chris
