### ISSUE TITLE
Factorised dot-product attention model

### ISSUE THREAD

**Issue by bashayerAlsalman** [google-research/scenic#323]
Hello everyone, 
I could not find the official implementation of Factorised dot-product attention, will it be provided soon? 
thank you

**Comment by MostafaDehghani** [comment]
Hi @bashayerAlsalman,
If you are referring to the factorized dot-product attention in ViViT project/paper, here you can find the code:
https://github.com/google-research/scenic/blob/main/scenic/projects/vivit/model_utils.py#L46

**Comment by bashayerAlsalman** [comment]
@MostafaDehghani Thank you, appreciated your fast response

**Comment by MostafaDehghani** [comment]
No problem at all :)
