### ISSUE TITLE
For OWL-ViT, is there a demo which shows the way using image patch as querys to do one-shot detection?

### ISSUE THREAD

**Issue by Edwardmark** [google-research/scenic#325]
Hi, thanks for your great work. And the demo of text zero-shot is amazing. 
For OWL-ViT, is there a demo which shows the way using image patch as querys to do one-shot detection?
Thanks.

**Comment by mjlm** [comment]
Hi, we're actively working on this demo and will let you know when it's available, hopefully some time next week.

**Comment by Edwardmark** [comment]
@mjlm And what prompt is used in coco evaluation? In the paper, it says it uses the seven best prompts, so what are the seven best text prompts? Thanks.

**Comment by AlexeyG** [comment]
The prompts can be found in the CLIP [repository](https://github.com/openai/CLIP/blob/e58d49454c92986a1d2a6a48add2333bbfbeaf51/notebooks/Prompt_Engineering_for_ImageNet.ipynb). During inference we used the 7 ensembling prompts from the colab.

**Comment by stevebottos** [comment]
Is this still in the works? I've been interested in seeing how image input queries could be used as well

**Comment by xishanhan** [comment]
> Hi, we're actively working on this demo and will let you know when it's available, hopefully some time next week.

Hi, is this one-shot detection demo finished? I'm also very interested in it and want to try.

**Comment by mjlm** [comment]
We're still working on this and will let you know here when the demo is ready. I re-opened the issue to keep track.

**Comment by xishanhan** [comment]
> We're still working on this and will let you know here when the demo is ready. I re-opened the issue to keep track.

That would be very nice, thank you!

**Comment by mjlm** [comment]
We just added a [Playground Colab](https://colab.research.google.com/github/google-research/scenic/blob/main/scenic/projects/owl_vit/notebooks/OWL_ViT_inference_playground.ipynb) with an interactive demo of both text-conditioned and image-conditioned detection:

<img src="../raw/main/scenic/projects/owl_vit/data/text_cond_wiki_stillife_1.gif" alt="OWL-ViT text inference demo" height="200"/>   <img src="../raw/main/scenic/projects/owl_vit/data/image_cond_wiki_circuits_1.gif" alt="OWL-ViT image inference demo" height="200"/>

The underlying code illustrates how to extract an embedding for a given image patch, specifically here: https://github.com/google-research/scenic/blob/main/scenic/projects/owl_vit/notebooks/inference.py#L110-L131

Let us know if you have any questions!

**Comment by xishanhan** [comment]
> We just added a [Playground Colab](https://colab.research.google.com/github/google-research/scenic/blob/main/scenic/projects/owl_vit/notebooks/OWL_ViT_inference_playground.ipynb) with an interactive demo of both text-conditioned and image-conditioned detection:
> 
> <img alt="OWL-ViT text inference demo" height="200" src="../raw/main/scenic/projects/owl_vit/data/text_cond_wiki_stillife_1.gif"> [ <img alt="OWL-ViT text inference demo" height="200" src="https://github.com/google-research/scenic/raw/main/scenic/projects/owl_vit/data/text_cond_wiki_stillife_1.gif"> ](https://github.com/google-research/scenic/raw/main/scenic/projects/owl_vit/data/text_cond_wiki_stillife_1.gif) [ ](https://github.com/google-research/scenic/raw/main/scenic/projects/owl_vit/data/text_cond_wiki_stillife_1.gif) <img alt="OWL-ViT image inference demo" height="200" src="../raw/main/scenic/projects/owl_vit/data/image_cond_wiki_circuits_1.gif"> [ ](https://github.com/google-research/scenic/raw/main/scenic/projects/owl_vit/data/image_cond_wiki_circuits_1.gif) <img alt="OWL-ViT image inference demo" height="200" src="https://github.com/google-research/scenic/raw/main/scenic/projects/owl_vit/data/image_cond_wiki_circuits_1.gif"> [ ](https://github.com/google-research/scenic/raw/main/scenic/projects/owl_vit/data/image_cond_wiki_circuits_1.gif)
> 
> The underlying code illustrates how to extract an embedding for a given image patch, specifically here: https://github.com/google-research/scenic/blob/main/scenic/projects/owl_vit/notebooks/inference.py#L110-L131
> 
> Let us know if you have any questions!

Thanks for your reply！I don't have any problems now.

**Comment by BIGBALLON** [comment]
Hi, @mjlm , thanks for your great  work!

**I wonder if there are any plans to implement multi-query image-conditioned detection.**

**Sometimes a single query image is often unable to capture all the features of an object, and using multiple query images to represent it can yield better results.**

thanks again!

**Comment by mjlm** [comment]
You can simply average the embeddings of multiple boxes to get a query embedding. This is how we implemented few-shot (i.e. more than one-shot) detection in the paper.

#890 will add example code for image-conditioned detection to the colab. The example shows how to get a `query_embedding` from the `class_embeddings` of the source (query) image. If you have e.g. two query embeddings representing the same object, you can simply do `two_shot_query_embedding = (query_embedding_1 + query_embedding_2) / 2`. This simple method worked for us. Another option would be to keep the embeddings separate, but map them to the same class after classification.
