### ISSUE TITLE
Interpolation of positional embedding

### ISSUE THREAD

**Issue by wusize** [google-research/scenic#327]
Hi!

When you interpolated the positional embedding, did you reshape it into a 2d feature map and apply bilinear interpolation or just use a 1d linear interpilation directly on the embedding vector?

**Comment by MostafaDehghani** [comment]
Hi @wusize, 
Can you provide more context? Which project this question is about?

**Comment by wusize** [comment]
Hi! Thanks for your response. The question is about the [OWL-ViT](https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit).

**Comment by AlexeyG** [comment]
Hi @wusize,

Thanks for your question and your interest in OWL-ViT!

The visual tower positional embeddings were resized as a 2D grid using the `scipy.ndimage.zoom` function with `order=1`. Hope this clears things up.

~Alexey
