### ISSUE TITLE
For owl_vit, what is the inference time in gpu?

### ISSUE THREAD

**Issue by Edwardmark** [google-research/scenic#330]
Hi, for owl_vit, what is the inference time in gpu? I tried your demo, and found out it takes more than 3 second for one image forwad. Is that true?

**Comment by mjlm** [comment]
No, fortunately OWL-ViT is faster than that :)

For simplicity, the minimal example doesn't apply just-in-time compilation. [Here](https://colab.research.google.com/gist/mjlm/193452ef1970d2c64537f3ac0cbde635/owl-vit-inference-speed.ipynb) is a colab that shows how to get more realistic numbers (scroll down to the bottom of the colab).

With compilation, the time is down to 200ms per forward pass. Note that this is just a rough estimate. Further optimizations, e.g. for I/O, would be necessary for a proper benchmark setting.

![image](https://user-images.githubusercontent.com/5418069/170239424-48996368-69b7-41b5-afe9-4b54b011f98a.png)
