### ISSUE TITLE
Is it possible to inference OWL-ViT with smaller input resolution?

### ISSUE THREAD

**Issue by Edwardmark** [google-research/scenic#336]
Hi, OWL-ViT is amazing but the inference speed is not so fast. I am wondering if it is possible to inference the model with smaller input resolution. For example, how to inference 224x224 image with positional embedding trained with 768x768?

Thanks.

**Comment by AlexeyG** [comment]
Hi @Edwardmark,

Happy to hear that you like OWL-ViT. Thanks!

Regarding improving the inference speed, there are several knobs that can be tuned to improve it. Reducing the input image resolution is one, and using a smaller model is another one. Having said that, you should expect that turning down either of these knobs will  reduce the models performance.

We have not attempted downsizing the embeddings of a model trained on larger resolutions such that it could be applied to smaller input resolutions. It might work, but needs further evaluation.

We have several smaller models we trained for the paper (e.g. B/32 or B/16), and are considering releasing them if that's something that would be useful for the community.

**Comment by Edwardmark** [comment]
@AlexeyG Thanks. I think smaller model would really help, looking forward to the release.

**Comment by Edwardmark** [comment]
@AlexeyG @mjlm So how to convert the owl-vit model to tensorflow? Is there a demo to show that？ Thanks.
