### ISSUE TITLE
For scenic model, how to convert it to onnx or tensorRT ?

### ISSUE THREAD

**Issue by Edwardmark** [google-research/scenic#337]
Hi, could you please tell me if it is possible to convert scenic model to onnx  or tensorRT? Thanks.

**Comment by MostafaDehghani** [comment]
Hi @Edwardmark,

We don't have any particular tooling to support that (and not sure if I know anyone who did that before). We only support JAX2TF (export Scenic models to tensorflow model).

**Comment by Edwardmark** [comment]
@MostafaDehghani could you please tell me how to convert scenic to tensorflow? Thanks.

**Comment by MostafaDehghani** [comment]
Oh, sorry! I closed the issue by accident! :D

**Comment by MostafaDehghani** [comment]
Here you can find the code for doing that: https://github.com/google-research/scenic/blob/main/scenic/common_lib/export_utils.py

**Comment by Edwardmark** [comment]
@MostafaDehghani Thanks. I will try it.

**Comment by Edwardmark** [comment]
@MostafaDehghani is there a example for how to use the code? I want to convert OWL-VIT model to tensorflow frozen model (protobuf).

**Comment by Edwardmark** [comment]
@MostafaDehghani hi, is there any update?

**Comment by mjlm** [comment]
Should be fixed now as of #341.

**Comment by Edwardmark** [comment]
@mjlm  Thanks. It really helps.
