### ISSUE TITLE
vit demo not running past one epoch

### ISSUE THREAD

**Issue by brettkoonce** [google-research/scenic#37]
when running the base config, eg:

> time python3 main.py --config=projects/baselines/configs/imagenet/imagenet_vit_config.py --workdir=./fp32-test

with the only modification being a batch size of 48 (i am using 2 nvidia gpu's to run things)

at the end of the first epoch the code dies:

```
I0929 15:28:35.031877 139903179183936 local.py:41] Setting work unit notes: 0.4% @9277, 0.3 steps/s, ETA: 153959 min (90 min : 0.0% checkpoint, 23.7% eval)
I0929 15:28:35.042148 139882655643392 logging_writer.py:34] [9277] steps_per_sec=0.259032
I0929 15:29:42.340490 139903179183936 local.py:41] Setting work unit notes: 0.4% @9281, 0.1 steps/s, ETA: 671072 min (91 min : 0.0% checkpoint, 23.4% eval)
I0929 15:29:42.351035 139882655643392 logging_writer.py:34] [9281] steps_per_sec=0.059428
I0929 15:31:58.488358 139903179183936 local.py:41] Setting work unit notes: 0.4% @9283, 0.0 steps/s, ETA: 2713548 min (93 min : 0.0% checkpoint, 22.8% eval)
I0929 15:31:58.627787 139882655643392 logging_writer.py:34] [9283] steps_per_sec=0.014697
Killed

real    93m53.945s
user    222m56.696s
sys     63m40.052s

```

do you have any suggestions on things to check/have you seen this before?

**Comment by brettkoonce** [comment]
might be upstream fwiw as well: https://github.com/google/jax/issues/8044

**Comment by MostafaDehghani** [comment]
I'm not 100% sure, but this looks like you ran out of memory when it started doing validation, which is done [at the end of each epoch](https://github.com/google-research/scenic/blob/main/scenic/train_lib/classification_trainer.py#L293).
To check this, can you set `log_eval_steps`  to a small number and also play with `steps_per_eval` in your config file?

**Comment by brettkoonce** [comment]
finally managed to test things a bit more locally.  you are correct, it is a memory issue.  having said that, it's not really scenic's fault, just that the code loads imagenet into memory by default (eg ~165GB of ram usage) and if you have less then that things will get wonky!  training fine here!
