### ISSUE TITLE
variable "simple_tokenizer" is missing

### ISSUE THREAD

**Issue by TLi347** [google-research/scenic#374]
In the 10 line in scenic/projects/baselines/clip/tokenizer.py:

       ` from clip.simple_tokenizer import SimpleTokenizer`

But there are no objects or files including "simple_tokenizer"

**Comment by AlexeyG** [comment]
This file is a part of the official CLIP code release:

https://github.com/openai/CLIP/blob/main/clip/simple_tokenizer.py
