### ISSUE TITLE
Initialization of model 

### ISSUE THREAD

**Issue by cakeinspace** [google-research/scenic#407]
I noticed that flax provides multiple initializers in the form of flax.linen.initializers. Looking through the unet code i couldnt see it being used. So i wanted to know the current initialization strategy. Is it completely random and how it compares to the way networks are initialized in pytorch and will it affect the training dynamics, convergence etc.

**Comment by MostafaDehghani** [comment]
Any flax layer has an argument specifying the initialization. If we don't specify it (e.g., convs in the UNet code in Scenic), it uses the default from flax: https://github.com/google-research/scenic/blob/31e55cdadc3f02f48e0d700ea943d2f9d43c85b1/scenic/model_lib/layers/masked_layers.py#L438
Hope this is clear.

**Comment by cakeinspace** [comment]
hey yes it does thanks a lot for your clarification.  i will close it
