### ISSUE TITLE
OWL-ViT models pre-trained checkpoints loading problem

### ISSUE THREAD

**Issue by farrokhsiar** [google-research/scenic#449]
I have downloaded the pre-trained checkpoint for OWL-ViT and when I try to load it on my personal machine, as a part of OWL-ViT minimal example.ipynb, but I get this error: 
```---------------------------------------------------------------------------
ExtraData                                 Traceback (most recent call last)
Input In [7], in <cell line: 1>()
----> 1 variables = module.load_variables(config.init_from.checkpoint_path)

File /opt/conda/miniconda3/lib/python3.8/site-packages/scenic/projects/owl_vit/models.py:44, in TextZeroShotDetectionModule.load_variables(self, checkpoint_path)
     42 @nn.nowrap
     43 def load_variables(self, checkpoint_path: str) -> Mapping[str, Any]:
---> 44   restored = checkpoints.restore_checkpoint(checkpoint_path, target=None)
     45   return {'params': restored['optimizer']['target']}

File /opt/conda/miniconda3/lib/python3.8/site-packages/flax/training/checkpoints.py:456, in restore_checkpoint(ckpt_dir, target, step, prefix, parallel, gda_manager)
    453   else:
    454     checkpoint_contents = fp.read()
--> 456 state_dict = serialization.msgpack_restore(checkpoint_contents)
    457 state_dict = _restore_gdas(state_dict, target, ckpt_path, step, gda_manager)
    459 if target is None:

File /opt/conda/miniconda3/lib/python3.8/site-packages/flax/serialization.py:350, in msgpack_restore(encoded_pytree)
    337 def msgpack_restore(encoded_pytree: bytes):
    338   """Restore data structure from bytes in msgpack format.
    339 
    340   Low-level function that only supports python trees with array leaves,
   (...)
    348     and array leaves.
    349   """
--> 350   state_dict = msgpack.unpackb(
    351       encoded_pytree, ext_hook=_msgpack_ext_unpack, raw=False)
    352   return _unchunk_array_leaves_in_place(state_dict)

File msgpack/_unpacker.pyx:201, in msgpack._cmsgpack.unpackb()

ExtraData: unpack(b) received extra data.```

Also, here are the TF related libraries:
```
flax                              0.5.3
jax                               0.3.16
jaxlib                            0.3.15
tensorboard                       2.9.1
tensorboard-data-server           0.6.1
tensorboard-plugin-wit            1.8.1
tensorflow                        2.9.1
tensorflow-addons                 0.17.1
tensorflow-datasets               4.6.0
tensorflow-estimator              2.9.0
tensorflow-hub                    0.12.0
tensorflow-io-gcs-filesystem      0.26.0
tensorflow-metadata               1.9.0
tensorflow-model-optimization     0.7.3
tensorflow-text                   2.9.0
tensorstore                       0.1.22
```
Any idea on what causes this problem?

**Comment by mjlm** [comment]
Hi,

I just double-checked, the minimal colab works in the public runtime. So I can think of two possible issues:

1. Perhaps the checkpoint download is incomplete, or the file you're trying to load does not match the config (e.g. downloading the B/16 checkpoint but using the B/32 config).
2. Some package incompatibility. I pasted the output of `pip freeze` in the (working) colab here: https://gist.github.com/mjlm/138000b54ccfaa35e4f8ffd9ff29ddad. Try using the same versions of `flax` and `msgpack`. Of course, if you can, the easiest would be to start from a clean environment and use the same `pip install ...` commands as in the colab.

Let me know how it goes!

Matthias

**Comment by farrokhsiar** [comment]
Thanks mjlm.
To close the ticket, I could solve it by moving the file to another gs bucket. Apparently, the path to checkpoint cannot be in local directory.

**Comment by mjlm** [comment]
Great that it works now, thanks for following up. I'll look into why it doesn't work with local files.

**Comment by YueYaoUoS** [comment]
Hi, is there any update on loading the checkpoint from the local directory?
