### ISSUE TITLE
Notebook callback name 

### ISSUE THREAD

**Issue by twjang** [google-research/scenic#463]
Hello, I came across this code.

https://github.com/google-research/scenic/blob/471da6bff844b102ef1527bc3489b3290a4f2d21/scenic/projects/owl_vit/notebooks/interactive.py#L18

Should it be changed to `'image_conditioning_py_callback'`, or is it okay to leave it as it is?

**Comment by mjlm** [comment]
Thanks for pointing this out. I think you're right, although it's not a big problem in practice since you can just re-run the corresponding Colab cell to re-register the appropriate callback. Fixed in #464
