### ISSUE TITLE
[OWL-ViT] De-duplication results.

### ISSUE THREAD

**Issue by wavinflaghxm** [google-research/scenic#508]
Hi, thanks for the nice work!
Can you provide the annotation file of the training dataset after de-duplication (Table A2)?

**Comment by AlexeyG** [comment]
Hi @wavinflaghxm 

We prepared a list of image IDs removed as a result of de-duplication. This can be used to filter the original annotation files.
You can find the zip file with 3 JSONs listing the removed IDs [here](https://drive.google.com/file/d/1SkdnDTaVNifBHH6AjzBWFmBQEaSSUXtU/view?usp=sharing).

Please let me know if you have further questions.

Best,
Alexey
