### ISSUE TITLE
AttributeError: module 'jaxlib.pocketfft' has no attribute 'pocketfft'

### ISSUE THREAD

**Issue by zzzzrrrrrrr** [google-research/scenic#511]
After running the pip install -r requirements.txt, I still can't run the code and the error is "AttributeError: module 'jaxlib.pocketfft' has no attribute 'pocketfft'". How can I install pocketfft?

**Comment by AlexeyG** [comment]
This looks like a question about JAX. Probably best asked there (i.e. https://github.com/google/jax)
