### ISSUE TITLE
The Inference time of OWL_VIT?

### ISSUE THREAD

**Issue by ngthanhtin** [google-research/scenic#530]
Hi @ayp-google, @mjlm , @general,
Thank you for your great work on open-vocabulary detection. I am a student working on open-world detection.
I have a question related to the inference time on an image. When I run the [code](https://colab.research.google.com/github/google-research/scenic/blob/main/scenic/projects/owl_vit/notebooks/OWL_ViT_minimal_example.ipynb) (following your provided notebooks) on an image, it takes about 30 seconds to finish which is too long for a detection process. I am sure that I have turned on my GPU, so do you know how to improve the inference time?

Best,
Tin

**Comment by FrancescoSaverioZuppichini** [comment]
Get a better GPU, colab uses a `t4` that is a very power efficient GPU but not as powerful as a v100

**Comment by mjlm** [comment]
Please see #330:

> For simplicity, the minimal example doesn't apply just-in-time compilation. [Here](https://colab.research.google.com/gist/mjlm/193452ef1970d2c64537f3ac0cbde635/owl-vit-inference-speed.ipynb) is a colab that shows how to get more realistic numbers (scroll down to the bottom of the colab).
>
> With compilation, the time is down to 200ms per forward pass. Note that this is just a rough estimate. Further optimizations, e.g. for I/O, would be necessary for a proper benchmark setting.
