### ISSUE TITLE
Questions about OWL-ViT TFLite conversion

### ISSUE THREAD

**Issue by JordanH-app** [google-research/scenic#534]
Hello!

I'm interested in trying a TFLite version of OWL-ViT for zero-shot object detection.
I've tried the Google Colab notebook for TFlite conversion but I'm facing two problems.

Problem 1

The "end-to-end" tflite file is about 1.5GB, while the pb file is only 60MB.
Why is the TFlite model much larger than the Tensorflow one? I used to think that tflite models are lighter than their Tensorflow version.
I tried adding the option `converter.optimizations = [tf.lite.Optimize.DEFAULT]` during conversion, but the resulting model file was still about 1GB.

Problem 2

Three weeks ago, I successfully converted "embed_images", "predict_boxes" and "predict_logits" modules to TFLite by setting `MAX_NUM_QUERIES` to 1 (when using the default `MAX_NUM_QUERIES = 100`, my session kept crashing due to a lack of memory).  
However, today my session crashed when trying to convert the "embed_images" module regardless of the `MAX_NUM_QUERIES` value. 
Is Google Colab Pro required to successfully convert OWL-ViT to TFLite?

I think the two problems are related at some point, but I'm not sure about what to investigate.

I don't think it's related to the problems above, but  I appended `!sed -i '/    "tf-models-official",/d' ./setup.py` after cloning scenic. Without this command, pip keeps trying to solve package dependencies when installing this repository.

Does someone have a hint about what's going wrong?
Let me know if you need more details.

Jordan

**Comment by mjlm** [comment]
Hi Jordan,

Here are some thoughts on the issues you mention:

**Problem 1**: It looks to me like the tflite file includes the model parameters, but the pb file does not. The parameters are on the order of 1GB depending on the architecture. This will be hard to get around without reducing the architecture size. Quantization of model parameters might be a way to save space but we haven't tried that.

**Problem 2**: I have noticed that the public CPU runtime has pretty limited RAM. Perhaps try with the GPU or TPU runtimes, which may have more RAM. You can also run a Jupyter Notebook kernel locally on your machine and connect Colab to that ([instructions](https://research.google.com/colaboratory/local-runtimes.html)), which may help if your machine has enough RAM.

**tf-models-official**: We're aware of the dependency conflicts and will remove tf-models-official from setup.py soon. As you say, this is probably not related to the other issues.

Hope this helps!

**Comment by JordanH-app** [comment]
Hi Matthias,
 
Thank you very much for your support!
 
Nothing is decided yet, but there is a chance that my team investigates post-training quantization of OWL-ViT.
 
I tried converting OWL-ViT to TFLite on GPU and TPU runtimes but the sessions crashed too. 
I'll give it a try on a local machine by following the instructions you provided. 
 
 For the moment, I think this issue can be closed.

Jordan

**Comment by mjlm** [comment]
Sounds good. Please let me know how the quantization goes!
