### ISSUE TITLE
[OWL-ViT] Fine-tuning a trained OWL-ViT model on a small dataset

### ISSUE THREAD

**Issue by ronhag** [google-research/scenic#542]
Hi there!

Thanks for the great work with OWL-ViT and the rest of the library.

I was wondering if you guys could give some ideas as to how to finetune a pretrained owl-vit model to a small dataset.

Also, I'm curious as to what are your thoughts about the following:
- would it be enough to fine-tune the learned shift and scale only? 
- My intuition about the learned shift and scale is to learn a mapping that drives apart background boxes from the query embedding, is this roughly right?

Thanks a lot!

**Comment by ronhag** [comment]
Noted! Thanks for overview. I'll reopen if I have other questions :)

**Comment by kopyl** [comment]
@mjlm do you know any clearer guide on fine-tuning?

At least on how a dataset should be organized and how to use it on fine-tuning
