### ISSUE TITLE
tf-models-official import in video_ops

### ISSUE THREAD

**Issue by mmaz** [google-research/scenic#544]
Hi, I'm exploring the MBT project and wasn't sure which package resolves the following import in [`scenic/dataset_lib/video_ops.py`](https://github.com/google-research/scenic/blob/87aedb0e5dc19d8536e96d2e6210ac569b55bf7f/scenic/dataset_lib/video_ops.py#L35)

`from official.vision.image_classification import augment`

Is this available in another package besides `tf-models-official` now? I saw that commit 82b8cfed removes `tf-models-official` (is the intent for projects to pin to a specific version, e.g., in [`requirements.txt`](https://github.com/google-research/scenic/blob/main/scenic/projects/mbt/requirements.txt)?)

Thanks!

**Comment by anjugopinath** [comment]
I am getting the same error.  What is the fix?

**Comment by Mohamedellebody** [comment]
replace official.vision.image_classification by official.legacy.image_classification
