### ISSUE TITLE
OWL-ViT: Tensorflow checkpoints as downloads

### ISSUE THREAD

**Issue by maxfrei750** [google-research/scenic#547]
Hi @mjlm! Thanks for your awesome work on OWL-ViT!

IMHO, it would be convenient to users and also more sustainable, if you would make the checkpoints for tensorflow available as downloads. Like that, people would not have to convert them themselves using the [export notebook](https://colab.research.google.com/github/google-research/scenic/blob/main/scenic/projects/owl_vit/notebooks/OWL_ViT_Export_JAX_model_to_TensorFlow_SavedModel.ipynb).

Thanks for considering it.

**Comment by mjlm** [comment]
Hi Max,

Thanks for the suggestion. I added the tf.SavedModel versions to the cloud storage bucket here:
```
gs://scenic-bucket/owl_vit/checkpoints/clip_vit_b16_6171dab_tf_model/
gs://scenic-bucket/owl_vit/checkpoints/clip_vit_b32_b0203fc_tf_model/
gs://scenic-bucket/owl_vit/checkpoints/clip_vit_l14_d83d374_tf_model/
```

We'll update the README soon to include this info.

**Comment by maxfrei750** [comment]
Thanks for the quick reply!

I tried to download the first file using https://storage.googleapis.com/scenic-bucket/owl_vit/checkpoints/clip_vit_b16_6171dab_tf_model/, but received 

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: scenic-bucket/owl_vit/checkpoints/clip_vit_b16_6171dab_tf_model</Details>
</Error>
```

Am I missing something?

Thanks!

**Comment by mjlm** [comment]
You can access the files in code like this: `tf.io.gfile.listdir('gs://scenic-bucket/owl_vit/checkpoints/clip_vit_b32_b0203fc_tf_model')`.

**Comment by maxfrei750** [comment]
Thanks for the clarification, but I was looking for a way to directly download the files to my local drive. Is there a way to do this as of now?

**Comment by mjlm** [comment]
You should be able use `tf.io.gfile.copy` on your local machine to copy from a gs:// path to a local path. https://www.tensorflow.org/api_docs/python/tf/io/gfile/copy
