### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tf_nightly==2.9.0.dev20220401 (from scenic) (from versions: none)

### ISSUE THREAD

**Issue by Claire874** [google-research/scenic#551]
When I tried to install scenic
I run ` pip install .` and get this error.
**ERROR: Could not find a version that satisfies the requirement tf-nightly (from versions: none)
ERROR: No matching distribution found for tf-nightly**
when I tried to run `!pip install tf-nightly`
here is the result:
!pip install tf-nightly
pip install . install tf-nightly
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.ngc.nvidia.com
Processing /misc/export3/tansihan/scenic
  Preparing metadata (setup.py) ... done
Collecting install
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4d/c8/8cbca135f9e167810756ea2bc34b028501936675fcbd7dadccf752fa4622/install-1.3.5-py3-none-any.whl (3.2 kB)
ERROR: Could not find a version that satisfies the requirement tf-nightly (from versions: none)
ERROR: No matching distribution found for tf-nightly

My python version is 3.9.0
I wonder why this happens and how to solve it.

**Comment by Claire874** [comment]
`pip install . -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com`
I run it in this way, seems successfully

**Comment by rdilip** [comment]
Seconding that @Claire874 's solution worked for me -- that said, it would be nice to get this dependency fixed.

**Comment by mjlm** [comment]
Should be fixed by f84823a.
