### ISSUE TITLE
[OWL-ViT] Support for instance segmentation?

### ISSUE THREAD

**Issue by ronhag** [google-research/scenic#554]
Hi there!

I was wondering if you guys are considering adding support for instance segmentation. It'd be really awesome!

Do you have any ideas as how to implement such feature? Do you think that a DETR-like approach would work? 

Given that we don't have a decoder in OWL-ViT (unlike DETR), it may be that simply adding an FPN-style CNN after the attention maps of the OWL-ViT encoder would not work. Any intuition here? :)

**Comment by raymond1123** [comment]
I am looking forward the instance segmentation too. 
@ronhag I just mentioned a paper "Image Segmentation Using Text and Image Prompts", not sure whether this is inspired to you.

**Comment by mjlm** [comment]
We provide one model that predicts instance segmentation masks for detected objects. The `Models with segmentation mask head` section in the [example colab](https://colab.sandbox.google.com/github/google-research/scenic/blob/main/scenic/projects/owl_vit/notebooks/OWL_ViT_minimal_example.ipynb) illustrates how to use it.
