### ISSUE TITLE
[OWL-ViT] Checkpoint for R50+H/32 architecture 

### ISSUE THREAD

**Issue by ronhag** [google-research/scenic#559]
Hi scenic team!

Will you guys by any chance release the **R50+H/32** checkpoint? From reading the paper (Table 2), it seems that version is the best-performing model for one or few-shot learning (please correct me if I'm wrong).

Thanks in advance!

**Comment by mjlm** [comment]
Hi,

We're not planning to release the R50+H/32 checkpoint but the CLIP L/14 checkpoint should perform similar or better (we hadn't trained that yet when we made Table 2 for the paper). Please try that and let us know how it goes.

Best,
Matthias
