### ISSUE TITLE
Why does zero-shot detection always have an output in target image? 

### ISSUE THREAD

**Issue by timothylimyl** [google-research/scenic#591]
It seems that even if the objects is clearly not in the target image, it will give a prediction regardless of how high I put the confidence/IOU threshold to be.

I am thinking of using the zero-shot detection as an automatic search function. It searches for similar objects in a datasets based off the query from an image containing the object given by the user. It won't make much sense if it also queries out a bunch of false positives cause then you might else well look through the dataset yourself to find the presence of the object of interest.  

Any ideas on how could I potentially fix this? Is there a similarity threshold that we can set?

**Comment by mjlm** [comment]
I assume you're referring to the [inference playground colab](https://colab.sandbox.google.com/github/google-research/scenic/blob/main/scenic/projects/owl_vit/notebooks/OWL_ViT_inference_playground.ipynb) or the [web demo](https://owlvit-tgc6as3cga-ew.a.run.app/) (please let me know if not). Both of these are designed for interactive exploration and will scale the prediction such that at least one box is always displayed for each query. This re-scaling is just for display, and you can of course set your own threshold when using the model for your application.

To understand the raw outputs of the model, have a look at the [minimal colab](https://colab.sandbox.google.com/github/google-research/scenic/blob/main/scenic/projects/owl_vit/notebooks/OWL_ViT_minimal_example.ipynb). The raw output of the model is a set of boxes, and a score (probability) for each box+query pair.
