### ISSUE TITLE
[OWL-ViT] Finetuning l14 on own dataset

### ISSUE THREAD

**Issue by 25icecreamflavors** [google-research/scenic#611]
Hello, is it possible to finetune owl-vit14 on my own dataset? I saw a script for finetuning 32 version, but I really need l14. Also, what format of the dataset should be there to finetune? How do I put my data (images, texts, boxes) in the correct format?

**Comment by kopyl** [comment]
@25icecreamflavors hey :)

Could you please share the 32 version fine-tuning script?
