### ISSUE TITLE
OWL-ViT - No module named 'ott'  Error

### ISSUE THREAD

**Issue by ibaiGorordo** [google-research/scenic#620]
Hi, 

There seems to be some issue with the ott (https://github.com/ott-jax/ott) dependency, which is not installed correctly. 

## How to reproduce the error
Running the minimal example Colab notebook triggers the error. I have used it in the past without issues, so it might be some update to the code that is triggering the issue
https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit#minimal-example

**Comment by ibaiGorordo** [comment]
##Update 

The issue seems to be with this commit where they switched from `setup.cfg to`  `pyproject.toml` for the build
https://github.com/ott-jax/ott/commit/5d0e9d7a827b880dd1272b6f2b01d4525d0a85c5

Using pip>=22.3 seems to solve the issue.

**Comment by mjlm** [comment]
This should be fixed in #623 .
