### ISSUE TITLE
你好，在win系统，我下载了代码，怎么配环境呢

### ISSUE THREAD

**Issue by God-song** [google-research/scenic#639]
![image](https://user-images.githubusercontent.com/38659788/210333782-d6f044a5-09a9-4e9b-996e-ebf9487941f7.png)
通过这个命令一直报错，是只能在linux系统通过这个命令安装吗

**Comment by mjlm** [comment]
我只在 Linux 上测试过这个。 要使其在 Windows 上运行，您可能必须从源代码构建 jax：https://jax.readthedocs.io/en/latest/developer.html#additional-notes-for-building-jaxlib-from-source-on- 视窗

然而，这可能很难。 只使用 Linux 可能更容易。
