### ISSUE TITLE
[OWL-ViT] More pretrained checkpoints

### ISSUE THREAD

**Issue by wavinflaghxm** [google-research/scenic#640]
Hi scenic team!

Will you by any chance release more pretrained checkpoints? In particular, _LVIS base training_ models in Table 1.

Thanks!

**Comment by mjlm** [comment]
We're not planning on releasing the LVIS-base checkpoints. For practical use of OWL-ViT, I recommend using the checkpoints trained on O365/VG, which perform much better. If you want to evaluate the LVIS-trained checkpoints for research purposes, feel free to email me at mjlm@google.com.
