### ISSUE TITLE
[OWL-ViT] A little confusion about the training code

### ISSUE THREAD

**Issue by wangxinxin08** [google-research/scenic#641]
In ` TextZeroShotDetectionModule`, the `query_mask` is obtained by the following code: https://github.com/google-research/scenic/blob/main/scenic/projects/owl_vit/models.py#L157. However,  the padding query is empty string and when the padding query is converted to `text_queries_tokenized` by `ClipTokenizeQueries` preprocess op, the tokenized query will be [49406, 49407, 0, 0, ..., 0]. That is, the `query_mask` will be all ones. Is this the desired behavior？

**Comment by mjlm** [comment]
This is a good observation. It is not really the intended behavior, but it doesn't seem to be a big issue and we obtained all results with this bug, so we kept it like this in the code.
