### ISSUE TITLE
Freezing Backbone Layers

### ISSUE THREAD

**Issue by akornilo** [google-research/scenic#656]
I am working on Fine-Tuning the Owl-Vit models and an interested in freezing the "Clip Backbone" and only training the final heads. 
Is there an easy way to set this up in the config?

I imagine that I can set the learning rate to 0, but that would not mark them as frozen AND avoid computing the gradient (to save time).

```  sched_txt = ml_collections.ConfigDict()
  sched_txt.re = '(backbone/clip/.*)'
  sched_txt.lr_configs = ml_collections.ConfigDict({
      'learning_rate_schedule': 'compound',
      'factors': 'constant',
      'base_learning_rate': 0,
  })
```

Any recommendations on the best practice for this would be appreciated

**Comment by mjlm** [comment]
I think you can set `sched_txt.lr_configs = None` to freeze these parameters. This should then exclude these parameters from optimization [here](https://github.com/google-research/scenic/blob/main/scenic/train_lib/optax.py#L179).

You could also try adding a `jax.lax.stop_gradient` between the backbone and the heads, if the above does not save compute.

Note that the code checks that every parameter is optimized by exactly one schedule, so you'll need to change the regular expression for the non-frozen parameters to the exact inverse of the frozen ones (e.g. using a negative lookahead expression).

**Comment by akornilo** [comment]
In reference to the first approach, I've tried to set-ups and they both break. 

I tried 
```
sched_backbone = ml_collections.ConfigDict()
sched_backbone.re = '(backbone/clip/.*)'
sched_backbone.lr_config = None
```
and got the error

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/scenic/scenic/projects/owl_vit/main.py", line 47, in <module>
    app.run(main=main)
  File "/home/ubuntu/scenic/scenic/app.py", line 65, in run
    app.run(functools.partial(_run_main, main=main))
  File "/home/ubuntu/.venv/scenic/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/ubuntu/.venv/scenic/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/ubuntu/scenic/scenic/app.py", line 101, in _run_main
    main(rng=rng, config=FLAGS.config, workdir=FLAGS.workdir, writer=writer)
  File "/home/ubuntu/scenic/scenic/projects/owl_vit/main.py", line 37, in main
    trainer.train(
  File "/home/ubuntu/scenic/scenic/projects/owl_vit/trainer.py", line 224, in train
    schedule = scenic_optax.make_schedule(config.get('schedule'))
  File "/home/ubuntu/scenic/scenic/train_lib/optax.py", line 161, in make_schedule
    schedule = [(re, name, create_schedule(lr_configs))
  File "/home/ubuntu/scenic/scenic/train_lib/optax.py", line 161, in <listcomp>
    schedule = [(re, name, create_schedule(lr_configs))
  File "/home/ubuntu/scenic/scenic/train_lib/optax.py", line 153, in create_schedule
    fn = get_learning_rate_fn(
  File "/home/ubuntu/scenic/scenic/train_lib/lr_schedules.py", line 287, in get_learning_rate_fn
    raise ValueError(
ValueError: `base_learning_rate` has to be defined in the lr_config.
```


---
**Attempt 2**
```
sched_backbone = ml_collections.ConfigDict()
sched_backbone.re = '(backbone/clip/.*)'
sched_backbone.lr_configs = ml_collections.ConfigDict()
```
and got the error trace

```
  File "/home/ubuntu/scenic/scenic/app.py", line 101, in _run_main
    main(rng=rng, config=FLAGS.config, workdir=FLAGS.workdir, writer=writer)
  File "/home/ubuntu/scenic/scenic/projects/owl_vit/main.py", line 37, in main
    trainer.train(
  File "/home/ubuntu/scenic/scenic/projects/owl_vit/trainer.py", line 224, in train
    schedule = scenic_optax.make_schedule(config.get('schedule'))
  File "/home/ubuntu/scenic/scenic/train_lib/optax.py", line 161, in make_schedule
    schedule = [(re, name, create_schedule(lr_configs))
  File "/home/ubuntu/scenic/scenic/train_lib/optax.py", line 161, in <listcomp>
    schedule = [(re, name, create_schedule(lr_configs))
  File "/home/ubuntu/scenic/scenic/train_lib/optax.py", line 153, in create_schedule
    fn = get_learning_rate_fn(
  File "/home/ubuntu/scenic/scenic/train_lib/lr_schedules.py", line 287, in get_learning_rate_fn
    raise ValueError(
ValueError: `base_learning_rate` has to be defined in the lr_config.
```

---
I traced through the code around the step you linked and the problem is that:

1. `frozen_mask, masks, scheds = _split_frozen(masks, scheds)`  identifies frozen layers based on things where the `sched` is `None`.
2.  The line above it, does pattern matching on the param names + finds the right schedule function based on whats encoded in our input config.
3. All the schedule functions are created [here](https://github.com/google-research/scenic/blob/main/scenic/train_lib/optax.py#L137) - but it is impossible to create a "None" schedule here - [this function](https://github.com/google-research/scenic/blob/main/scenic/train_lib/optax.py#L151) does not have a case for 'lr_config' being None.




---



Am I missing a simple workaround here? 



And could you clarify what you mean by `jax.lax.stop_gradient` I am not sure where I would add that in

**Comment by mjlm** [comment]
It's possible that we have never tested the freezing feature and that there's a bug. @AlexeyG , have you ever tried setting `sched_txt.lr_configs = None` to freeze params?

Regarding `stop_gradient`: This stops the flow of gradients during backprop, so adding `image_features = jax.lax.stop_gradient(image_features)` and `query_embeddings = jax.lax.stop_gradient(query_embeddings)` to the main model [here](https://github.com/google-research/scenic/blob/main/scenic/projects/owl_vit/models.py#L158) will stop backpropagation into the backbone and might save compute.

**Comment by akornilo** [comment]
Looks like the `stop_gradient` method worked for now...but
I believe there is in fact a bug here, I was able to partially fix it, but do not have insight to fix it entirely.

** Fix 1**
https://github.com/google-research/scenic/blob/261bb131ebe5119d09d63d27be76c517c0de64cc/scenic/train_lib/optax.py#L151

```
+    if lr_configs is not None:
+        fn = get_learning_rate_fn(
+            ml_collections.ConfigDict({'lr_configs': lr_configs}))
+    else:
+        return None
```

** Fix 2**:

https://github.com/google-research/scenic/blob/261bb131ebe5119d09d63d27be76c517c0de64cc/scenic/train_lib/optax.py#L178

```frozen_mask, masks, scheds = _split_frozen(masks, [value for _, value in scheds])
  not_frozen_mask = jax.tree_util.tree_map(operator.not_, frozen_mask)
  schedule_fns = [fn_base for fn_base, _ in (scheds or [])]
  schedule_base_lr = [base_lr for _, base_lr in (scheds or [])]
```

The problem at this point is that the "frozen masks" end up of the wrong shape and break during the update phase. So it be great if you could revisit the optmax set-up

**Comment by mjlm** [comment]
I think the right approach is to use `stop_gradient` *and* set the learning rate to 0.0 for the weights that should be frozen. That should save the computation of the gradients for the frozen weights and produce the right Optax state. Please re-open if this doesn't work.
