### ISSUE TITLE
ImportError in colab notebooks

### ISSUE THREAD

**Issue by amrzv** [google-research/scenic#663]
Hi.
When running both notebooks `scenic/projects/owl_vit/notebooks/OWL_ViT_{minimal_example,inference_playground}.ipynb` an ImportError raises at the very first import cell:
`ImportError: cannot import name 'monitoring' from 'jax' (/usr/local/lib/python3.8/dist-packages/jax/__init__.py)`
![image](https://user-images.githubusercontent.com/36787333/215318736-a7c97350-a592-4c14-9a06-a6e0f8621f77.png)

Running in default colab env with `jax==0.3.25`.

**Comment by PabloAMC** [comment]
I just had the same error with  flax version 0.6.4 and jax version 0.3.25
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/20182937/215537642-380ae649-11cd-45f7-930d-66233b45876d.png">

**Comment by PabloAMC** [comment]
To replicate it, use
````
!pip install jax
from jax import monitoring
````

**Comment by PabloAMC** [comment]
I think this is solved using
````
!pip install --upgrade pip
!pip install --upgrade "jax"
!pip install --upgrade jaxlib

from jax import monitoring
````

**Comment by AlexeyG** [comment]
This looks like a JAX issue rather than a Scenic-specific issues. I suggest you report it there.

Also great that you found a workaround @PabloAMC

**Comment by God-song** [comment]
![image](https://user-images.githubusercontent.com/38659788/215994700-b8d9af2c-6468-4c47-bcfd-53b55d7c29e6.png)
使用了这个，报这个错误

**Comment by mjlm** [comment]
I just tested this with `scenic/projects/owl_vit/notebooks/OWL_ViT_{minimal_example,inference_playground}.ipynb` and there are currently no import issues. Please file a new issue if imports break again.
