### ISSUE TITLE
[OWL-ViT] step by step instruction for finetuning on own local dataset

### ISSUE THREAD

**Issue by alexey-chaykin** [google-research/scenic#684]
Thank you for sharing your work. Is there any step by step instruction on how to train OWL-ViT on own local dataset?

From what mentioned in README, it is required to implement decoding ops, that converts TFDS dict, but what if all data is local? Is there any single class may be, that should be implemented and referred in config (how?) to supply own data?

P.S. It seems that should be "dataset: The dataset that has train_iter, eval_iter, meta_data, and optionally, test_iter." to be implemented and supplied to trainer, but exact instruction would be really helpful.

**Comment by kopyl** [comment]
@alexey-chaykin also curious about this.

Did you manage to find anything?

**Comment by magicleo** [comment]
Same question

**Comment by mjlm** [comment]
You can create a TFDS dataset from your local data as described at https://www.tensorflow.org/datasets/add_dataset. TFDS will write the dataset to a local folder, which you can then point TFDS to by setting the `TFDS_DATA_DIR` environment variable or by setting `data_dir` in calls to `tfds.builder` and `tfds.load`.
