### ISSUE TITLE
has no attribute 'pop'

### ISSUE THREAD

**Issue by jiangwenj02** [google-research/scenic#740]
I want to reproduce the results of ncr, while i stuck in "has no attribute 'pop'".
flax 0.5.3 jax 0.4.3

**Comment by MostafaDehghani** [comment]
Thank you @jiangwenj02 for posting this issue. This is a recent change in Flax. I believe we have to update the flax version in our `setup.py`. In the meantime, would you please install the latest version of Flax and see if this issue goes away?

**Comment by jiangwenj02** [comment]
at the begin i install the latest flax, however the latest flax removes the
optim, which also used in this code. so i solve the problem by installing
flax 0.53 and copy the pop function code from the latest flax and paste in
flax 0.53.

Mostafa Dehghani ***@***.***> 于 2023年4月3日周一 上午2:08写道：
