### ISSUE TITLE
ViT 22B checkpoint ?

### ISSUE THREAD

**Issue by jrabary** [google-research/scenic#754]
Hi,
Do you plan to release the model and checkpoint of ViT22b presented in "Scaling Vision Transformers to 22 Billion Parameters" ?

**Comment by MostafaDehghani** [comment]
Thanks @jrabary for the question. 
Unfortunately, we won't be able to release the ViT-22B checkpoint as it was trained on JFT (Google internal) dataset. We however trying to release the code, but it'll take some time to get all the approvals.

**Comment by nemonameless** [comment]
hi, when will the codes be released?

**Comment by nemonameless** [comment]
@MostafaDehghani
