### ISSUE TITLE
SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by MaxTeselkin** [google-research/scenic#772]
Hi! I am facing the following error:

```
SSL certificate problem: self signed certificate in certificate chain when reading metadata of gs://scenic-bucket/owl_vit/checkpoints/clip_vit_b32_b0203fc
```

Are there any ways to fix it?

**Comment by mjlm** [comment]
This looks like a configuration issue on your side. You can try to download the checkpoints manually using the links provided here: https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit#pretrained-checkpoints
