### ISSUE TITLE
[vid2seq] Access to the ASR data

### ISSUE THREAD

**Issue by PKUCSS** [google-research/scenic#776]
@antoyang  @a-nagrani  Dear authors, thanks for the great work. Could you please provide the transcribed ASR data of the YouCook2 and AcitivityNet Captions datasets you used in the experiments so that more followers could reproduce your results on these downstream datasets? 

I know that we can produce ASR data by utilizing open-sourced ASR models, calling commercial APIs, or processing the subtitle data from YouTube. However, I believe that access to your original ASR data used in the paper would contribute to the reproducibility of your work.

**Comment by antoyang** [comment]
Hi, unfortunately, releasing ASR data is not possible.

**Comment by PKUCSS** [comment]
Thanks anyway. I'm trying to reproduce the results in Huggingface Transformers and PyTorch, so I may propose other questions if I encounter some potential issues. Thanks again for your patient response.
