### ISSUE TITLE
[OWL-ViT] AttributeError: module 'jax.tree_util' has no attribute 'register_pytree_with_keys_class'

### ISSUE THREAD

**Issue by QHCV** [google-research/scenic#807]
'm having this problem when I run the code, can any of you help with this. Also, if I want to fine-tune my own dataset, how do I do it specifically, like handling the dataset format.

**Comment by xxiMiaxx** [comment]
hello @QHCV 

did you figure out how to resolve this error?

**Comment by mjlm** [comment]
This issue is unrelated to Scenic/OWL-ViT. The problem is that Colab does not (yet) seem to support new TPU setups, see https://github.com/google/flax/issues/3239. Try using a GPU runtime or run your own Colab kernel in a Google Cloud TPU VM.
