### ISSUE TITLE
Making the clip_vit_l14_with_masks model available as download

### ISSUE THREAD

**Issue by sheethalb** [google-research/scenic#811]
Hello,

thank you for your awesome project. please could you make the clip_vit_l14_with_masks model available as a download as well ? 
I have been able to locally run the first part of the minimal example, but cannot load the checkpoint through  gs://scenic-bucket/owl_vit/checkpoints/clip_vit_l14_with_masks_6c17944 due to a firewall. 

thanks!

**Comment by sheethalb** [comment]
this is the error i get when i try to load using 
variables = module.load_variables(config.init_from.checkpoint_path)

WARNING:jax._src.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
2023-06-15 13:25:34.517341: W tensorflow/tsl/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "ABORTED: All 10 retry attempts failed. The last failure: Error executing an HTTP request: HTTP response code 503 with body '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta type="copyright" content="Copyright (C) 1996-2016 The Squid Software Foundation and contributors">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"><!--
 /*
 * Copyright (C) 1996-2016 The Squid Software Foundation and contributors
 *
 * Squid software is distributed under GPLv2+ lice'".
...
...
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cert (path? access rights?)', error details: error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: none
         when reading metadata of gs://scenic-bucket/owl_vit/checkpoints/clip_vit_l14_with_masks_6c17944

**Comment by mjlm** [comment]
I'm not sure about the firewall settings on your end, but here's a direct download link (which we'll also add to the README): [clip_vit_l14_with_masks_6c17944](https://storage.googleapis.com/scenic-bucket/owl_vit/checkpoints/clip_vit_l14_with_masks_6c17944) (1.8 GB download).
