### ISSUE TITLE
[OWLv2] Model release

### ISSUE THREAD

**Issue by ronhag** [google-research/scenic#830]
Hi there! Exciting stuff with OWLv2! Any plans on releasing the training pipelines and models? That'd be so so cool!

**Comment by michaellee1** [comment]
👍

**Comment by michaellee1** [comment]
+1!

**Comment by mkolomeychenko** [comment]
+1!

**Comment by ronhag** [comment]
Hey @mjlm! Just a friendly ping. Again, super exciting work guys! Would really love to play around with it.

**Comment by meng-zha** [comment]
Exciting work! Look forward to the checkpoints!

**Comment by BIGBALLON** [comment]
Look forward to the checkpoints!

**Comment by mjlm** [comment]
Hi all, we just added the OWLv2 inference code and checkpoints, see https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit#pretrained-checkpoints and the updated [Colab](https://colab.sandbox.google.com/github/google-research/scenic/blob/main/scenic/projects/owl_vit/notebooks/OWL_ViT_minimal_example.ipynb).

The checkpoints are drop-in replacements compatible with OWLv1 code, so existing training and inference code should continue to work. The only change to the architecture is the objectness head, see changes to `models.py` in 17cc144993f855a66b7301e35e329962da13b060.

Some features of the OWLv2 training recipe, e.g. token dropping, are not yet implemented here. We're still thinking about if and when to add them.

**Comment by BIGBALLON** [comment]
@mjlm thanks for your amazing work.

BTW, is there any minmal example to show how to use the image as prompt(one/few shot image guided OVD) use OWL-V2 models?

thanks again

**Comment by romanticegg** [comment]
> Hi all, we just added the OWLv2 inference code and checkpoints, see https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit#pretrained-checkpoints and the updated [Colab](https://colab.sandbox.google.com/github/google-research/scenic/blob/main/scenic/projects/owl_vit/notebooks/OWL_ViT_minimal_example.ipynb).
> 
> The checkpoints are drop-in replacements compatible with OWLv1 code, so existing training and inference code should continue to work. The only change to the architecture is the objectness head, see changes to `models.py` in [17cc144](https://github.com/google-research/scenic/commit/17cc144993f855a66b7301e35e329962da13b060).
> 
> Some features of the OWLv2 training recipe, e.g. token dropping, are not yet implemented here. We're still thinking about if and when to add them.

thanks for your amazing work~ However, this pretrained model link can't be arrived, and I tried this way to get model: tf.io.gfile.listdir('gs://scenic-bucket/owl_vit/checkpoints/clip_vit_b32_b0203fc_tf_model')，but shows this error:tensorflow.python.framework.errors_impl.NotFoundError: Could not find directory gs://scenic-bucket/owl_vit/checkpoints/clip_vit_b32_b0203fc_tf_model. Could you please tell me how to solve it, thanks very much!

**Comment by zhanglu0704** [comment]
> Hi all, we just added the OWLv2 inference code and checkpoints, see https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit#pretrained-checkpoints and the updated [Colab](https://colab.sandbox.google.com/github/google-research/scenic/blob/main/scenic/projects/owl_vit/notebooks/OWL_ViT_minimal_example.ipynb).
> 
> The checkpoints are drop-in replacements compatible with OWLv1 code, so existing training and inference code should continue to work. The only change to the architecture is the objectness head, see changes to `models.py` in [17cc144](https://github.com/google-research/scenic/commit/17cc144993f855a66b7301e35e329962da13b060).
> 
> Some features of the OWLv2 training recipe, e.g. token dropping, are not yet implemented here. We're still thinking about if and when to add them.

We were successful in training OWL v1 with the given code, but it appears that our attempts to fine-tune OWL v2 have not been successful. It would be greatly appreciated if you could provide us with a method to fine-tune based on version V2.
