### ISSUE TITLE
[Vid2Seq] : Train/Pretrain Vid2Seq only with Visual Embeddings i.e. No Transcripts as input

### ISSUE THREAD

**Issue by anilbatra2185** [google-research/scenic#843]
hi @antoyang ,

Thanks for the great work.

I am trying to run the code for videos without any transcripts and interested in reproducing the result of `Row#3` in `Table 2` i.e. Pretraining with visual input and generative loss, and fine tuning on YouCook2. I wonder, which encoder type was used for the results - '`tmp`', '`t5_encoder`', '`cat_encoder`'. Moreover, as I am still learning JAX/Flax, so if you can help me with additional changes required in the code to run the required experiment.

Thanks in Advance!

**Comment by antoyang** [comment]
Hi, using the tmp encoder would ensure you only use visual features.
