### ISSUE TITLE
OWL-ViT inference playround: [module 'bokeh.plotting' has no attribute 'Figure']

### ISSUE THREAD

**Issue by YueYaoUoS** [google-research/scenic#846]
Hello,
When I ran the import block, this error was called. Could you please look into this issue? Many thanks!
` ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-13-6cf721b232cb>](https://localhost:8080/#) in <cell line: 13>()
     11 from scenic.projects.owl_vit.notebooks import inference
     12 from scenic.projects.owl_vit.notebooks import interactive
---> 13 from scenic.projects.owl_vit.notebooks import plotting
     14 from scipy.special import expit as sigmoid
     15 import skimage

[/content/scenic/projects/owl_vit/notebooks/plotting.py](https://localhost:8080/#) in <module>
    118                          fig_size: int = 900,
    119                          title: str = '',
--> 120                          tools: str = '') -> plotting.Figure:
    121   """Creates a Bokeh figure showing an image."""
    122   # Determine relative width and height from padding. We assume that padding is

AttributeError: module 'bokeh.plotting' has no attribute 'Figure' `

**Comment by tylertroy** [comment]
I got it working by downgrading bokeh to 2.4.3 with `pip install --upgrade bokeh=2.2.3`.

**Comment by YueYaoUoS** [comment]
**Solved:** By changing **'Figure'** to **'figure'** on line 120 and line 148 in /content/scenic/projects/owl_vit/notebooks/plotting.py

**Comment by YueYaoUoS** [comment]
**Solved:** By changing **'Figure'** to **'figure'** on line 120 and line 148 in /content/scenic/projects/owl_vit/notebooks/plotting.py
