### ISSUE TITLE
Incomplete Type Hints

### ISSUE THREAD

**Issue by kevinzakka** [google-research/scenic#88]
Thanks for this great release, really dig the design split for scenic! I noticed that submodules are partially type hinted (e.g. `common_lib` is but `dataset_lib` isn't) and was wondering if it would be possible to fix via a copybara setting. Would make it great to reuse some of the submodules in personal projects.

Cheers!

**Comment by MostafaDehghani** [comment]
Hi @kevinzakka Thanks for your interest in Scenic. 

Yes, we switched to forcing type annotation for code outside `scenic/projects` directory a while ago (For individual projects, the owners are in charge of this decision), and we are gradually adding missing type annotations, but there are still remaining ones as you also pointed out. 
The code in the GitHub repo is in sync with the internal code so any improvement we do internally will be immediately reflected on the external code. 
 
We hope that soon we have type annotation everywhere.  Btw, PRs for improving the code is always welcome and appreciated :)
