### ISSUE TITLE
OWL-VIT2 tf model downloads and conversion colab not working

### ISSUE THREAD

**Issue by drchrisscheier** [google-research/scenic#900]
thanks for providing these checkpoints! unfortunately, the tf model checkpoint links do not work:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: scenic-bucket/owl_vit/checkpoints/owl2-l14-1008-st-ngrams-ft-lvisbase_tf_model</Details>
</Error>

when running the tf conversion colab, it throws an error - my guess is that the colab is still working for v1 but not v2
TypeError                                 Traceback (most recent call last)
[<ipython-input-14-d8fb100ce315>](https://localhost:8080/#) in <cell line: 3>()
      1 assert tf.executing_eagerly(
      2 ), 'Use eager execution to avoid FailedPreconditionError.'
----> 3 convert_and_save_model(
      4     predict_fn,
      5     variables,

21 frames
    [... skipping hidden 5 frame]

[/usr/local/lib/python3.10/dist-packages/flax/linen/module.py](https://localhost:8080/#) in _call_wrapped_method(self, fun, args, kwargs)
    965       if _use_named_call:
    966         with jax.named_scope(_derive_profiling_name(self, fun)):
--> 967           y = fun(self, *args, **kwargs)
    968       else:
    969         y = fun(self, *args, **kwargs)

TypeError: TextZeroShotDetectionModule.box_predictor() takes 1 positional argument but 3 were given

**Comment by Aki1991** [comment]
I have finetuned the model with the steps given [here](https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit#fine-tuning) and have local checkpoint. Still I am getting same error.
