### ISSUE TITLE
[OWL-ViT] Bounding box all around the image 

### ISSUE THREAD

**Issue by toffo10** [google-research/scenic#923]
Hi,

I was testing out the one shot feature of the model in Google Colab and i've noticed that there's always an extra bounding box all around the image:
 
![download](https://github.com/google-research/scenic/assets/26899483/e58fe904-a9c1-4ca8-8b64-5b06c5b34d2b)

The same bounding box appears even in the minimal example in Google Colab:

![download (1)](https://github.com/google-research/scenic/assets/26899483/326d782d-fc71-44ee-8603-5a19b35f72f2)

Is there a way to filter it out?

Thank you

**Comment by mjlm** [comment]
How about simply removing boxes based on area? If the area relative to the image is, e.g., > 0.95, remove the box?
