### ISSUE TITLE
error caused by config.init_from.model_config = None

### ISSUE THREAD

**Issue by mlpen** [google-research/scenic#95]
Hi, 

Do you mind sharing the config.init_from.model_config for vivit project? The config py files in the repo set model_config to None, which causes error when trying to initialize model. 

Thanks!

**Comment by MostafaDehghani** [comment]
Can you specify the config you tried and share the error logs?

**Comment by hmph** [comment]
Thank you for bringing this up @mlpen.
This should be addressed by this [commit](https://github.com/google-research/scenic/commit/c3ae6d7b5dc829fafe204a92522a5983959561a0)

**Comment by mlpen** [comment]
Thanks! This works.

**Comment by MostafaDehghani** [comment]
Awesome! Thank you @hmph for sending the fix.
