### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by Zumbalamambo** [google-research/scenic#98]
Please share some example codes and tutorial codes on usage

**Comment by MostafaDehghani** [comment]
@Zumbalamambo Thanks for your interest in Scenic. 

Have you checked this: 
https://github.com/google-research/scenic#getting-started

Also the example colab here:
https://colab.sandbox.google.com/github/google-research/scenic/blob/main/scenic/common_lib/colabs/scenic_playground.ipynb

Do you have any specific question, about the code, project, or baselines?

**Comment by MostafaDehghani** [comment]
Closing this issue as there was no reply. Feel free to reopen if you had any additional question/comment.
