### ISSUE TITLE
What is the best way to do one-shot image-conditioned in Owl-v2

### ISSUE THREAD

**Issue by dienhoa** [google-research/scenic#989]
In Owl-ViT v1, to identify the optimal embedding vector representing the query image, as stated in the paper:

> We search for the most dissimilar class embedding within the group of class embeddings whose corresponding box has IoU > 0.65 with Q

This method aims to identify the foreground object.

However, in Owl-ViT v2, we now have the Objectness score for this purpose. I'm wondering if it would be better to use the Objectness score instead of the class embedding to identify the foreground object.

**Comment by mjlm** [comment]
Yes, in OWLv2 I'd use the objectness score. This is how the example in the [colab](https://colab.research.google.com/github/google-research/scenic/blob/main/scenic/projects/owl_vit/notebooks/OWL_ViT_minimal_example.ipynb) does it.
